config/routes.rb
Listas::Application.routes.draw do
  resources :animes

end

app/models/anime.rb
class Anime < ActiveRecord::Base
end

app/controllers/animes_controller.rb
class AnimesController < ApplicationController
  # GET /animes
  # GET /animes.xml
  def index
    @animes = Anime.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @animes }
    end
  end

  # GET /animes/1
  # GET /animes/1.xml
  def show
    @anime = Anime.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @anime }
    end
  end

  # GET /animes/new
  # GET /animes/new.xml
  def new
    @anime = Anime.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @anime }
    end
  end

  # GET /animes/1/edit
  def edit
    @anime = Anime.find(params[:id])
  end

  # POST /animes
  # POST /animes.xml
  def create
    @anime = Anime.new(params[:anime])

    respond_to do |format|
      if @anime.save
        format.html { redirect_to(@anime, :notice => 'Anime was successfully created.') }
        format.xml  { render :xml => @anime, :status => :created, :location => @anime }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @anime.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /animes/1
  # PUT /animes/1.xml
  def update
    @anime = Anime.find(params[:id])

    respond_to do |format|
      if @anime.update_attributes(params[:anime])
        format.html { redirect_to(@anime, :notice => 'Anime was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @anime.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /animes/1
  # DELETE /animes/1.xml
  def destroy
    @anime = Anime.find(params[:id])
    @anime.destroy

    respond_to do |format|
      format.html { redirect_to(animes_url) }
      format.xml  { head :ok }
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/helpers/animes_helper.rb
module AnimesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/animes/_form.html.erb
<%= form_for(@anime) do |f| %>
  <% if @anime.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@anime.errors.count, "error") %> prohibited this anime from being saved:</h2>

      <ul>
      <% @anime.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :nombre %><br />
    <%= f.text_field :nombre %>
  </div>
  <div class="field">
    <%= f.label :genero %><br />
    <%= f.text_field :genero %>
  </div>
  <div class="field">
    <%= f.label :descripcion %><br />
    <%= f.text_area :descripcion %>
  </div>
  <div class="field">
    <%= f.label :capitulos %><br />
    <%= f.text_field :capitulos %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/animes/edit.html.erb
<h1>Editing anime</h1>

<%= render 'form' %>

<%= link_to 'Show', @anime %> |
<%= link_to 'Back', animes_path %>

app/views/animes/index.html.erb
<h1>Listing animes</h1>

<table>
  <tr>
    <th>Nombre</th>
    <th>Genero</th>
    <th>Descripcion</th>
    <th>Capitulos</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @animes.each do |anime| %>
  <tr>
    <td><%= anime.nombre %></td>
    <td><%= anime.genero %></td>
    <td><%= anime.descripcion %></td>
    <td><%= anime.capitulos %></td>
    <td><%= link_to 'Show', anime %></td>
    <td><%= link_to 'Edit', edit_anime_path(anime) %></td>
    <td><%= link_to 'Destroy', anime, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Anime', new_anime_path %>

app/views/animes/new.html.erb
<h1>New anime</h1>

<%= render 'form' %>

<%= link_to 'Back', animes_path %>

app/views/animes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Nombre:</b>
  <%= @anime.nombre %>
</p>

<p>
  <b>Genero:</b>
  <%= @anime.genero %>
</p>

<p>
  <b>Descripcion:</b>
  <%= @anime.descripcion %>
</p>

<p>
  <b>Capitulos:</b>
  <%= @anime.capitulos %>
</p>


<%= link_to 'Edit', edit_anime_path(@anime) %> |
<%= link_to 'Back', animes_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Listas</title>
  <%= stylesheet_link_tag :all %>
  <%= javascript_include_tag :defaults %>
  <%= csrf_meta_tag %>
</head>
<body>

<%= yield %>

</body>
</html>